// src/App.tsx
import React from 'react';
import './About.css';
import BackgroundWithText from './BackgroundWithText';
import Extra from './extra';

function About() {
  return (
    <div className="About">
        <h1>What is gerr.ai? Gerr.ai is an app that allows users to easily draw district boundaires and 
            gain insights about the compactness of the district generated by GPT-3.5 Turbo. in order to do this, gerr.ai calculates the Polsby-Popper Score of the district shape, which compares the area of a district to its perimeter. The score ranges from 0 to 1, where 1 is the highest score. An ideal score is 1, indicating that the district is a perfect score.
            Realistically though, it is practically impossible to have a perfect circular district geographical features, the requirement to adhere to population equality, and the need to respect community boundaries and interests. The significane of Polsby-Popper
            score is often relative. It is used to compare the compactness of different districts within the same state or across different jurisdictions. Compact districts are important because
            not only do they reduce gerrymandering, but they help with voter engagement, public confidence, and electoral administration.
        </h1>
    </div>
  );
}

export default About;
